services:

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
    command: server

  config-server:
    image: 'config-server:0.0.1-SNAPSHOT'
    depends_on: [vault]
    ports:
      - 8888:8888
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_HOST: vault
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}

  greeting-service-prod:
    image: 'greeting-service:0.0.1-SNAPSHOT'
    depends_on: [config-server]
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}

  greeting-service-dev:
    image: 'greeting-service:0.0.1-SNAPSHOT'
    depends_on: [config-server]
    ports:
      - 8081:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}